### ISSUE TITLE
Error when evaluating

### ISSUE THREAD

**Issue by sean880304** [quanghuy0497/Mask_R-CNN#4]
Hi @quanghuy0497, 
when I run evaluation.py, I get this error:

```
mAP PASCAL 60.4166679084301 %
mAP COCO: 46.73611200104157 %
Traceback (most recent call last):
  File "evaluation.py", line 100, in <module>
    print("mean Precision: ", np.mean(mprecision) * 100, "%")
  File "<__array_function__ internals>", line 6, in mean
  File "/home/icmems/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3373, in mean
    out=out, **kwargs)
  File "/home/icmems/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 160, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
```
I think this shape error is because the image ground truth mask is 6, however, the predicted mask is only 5?
How or where do I solve this issue?
Thank you!!

**Comment by software93** [comment]
I have same issue did you solve it ?
I used this code for my custom dataset with 5 classes??
